pipeline {
    agent any
    tools {
        nodejs "Node-21"
    }
    environment {
        EC2_HOST = '13.232.7.145'
        EC2_USER = 'ubuntu'
        PRIVATE_KEY = '/var/lib/jenkins/ridham-ngnix-keypair.pem'
        DOCKER_IMAGE_NAME = 'ridhampatel/react-backend-project'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your Git repository
               script {
                   git branch: 'main', url: 'https://github.com/mansi-jayswal/Bacancy-FinalProject.git', credentialsId: 'ridham-app-git' 
                }
            }
        }

        stage('Build React App') {
            steps {
                // Build React app
                sh 'cd Client && npm install && npm run build && cd dist && pwd'
            }
        }
        
        stage('Transfer Frotend to EC2') {
            steps {
                script {
                    sh "rsync -avrx -e 'ssh -i ${PRIVATE_KEY} -o StrictHostKeyChecking=no' --delete /var/lib/jenkins/workspace/app.ridhampatel_prod/Client/dist/ ${EC2_USER}@${EC2_HOST}:/var/www/html/app"                  
                }
            }
        }
        
        stage('Build and push Docker Image') {
            steps {
                script {
                     // Build Docker image for Node Backend
                    sh 'whoami'
                    dockerImage = docker.build("${DOCKER_IMAGE_NAME}:nodebackend", " ./Server")
                    docker.withRegistry( '', 'docker-ridham' ) {  
                        dockerImage.push("nodebackend")
                    }
                }
            }
        }        
        
        stage('Run Docker Image on AWS EC2') {
            steps {
                script {
                    // This command will delete any contianer running on 5000 so this new docker container run easily.
                    def commands = """
                        cd 
                        docker rmi -f ridhampatel/react-backend-project || true
                        docker rm -f \$(docker ps -q --filter "publish=2452/tcp")
                        docker run -d -p 2452:3000 ridhampatel/react-backend-project:nodebackend
                        sudo systemctl restart nginx
                    """
                    // SSH into EC2 instance and pull Docker image
                    sshagent(['ec2-ssh']) {
                    sh "ssh -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} ${EC2_USER}@${EC2_HOST} '${commands}'"
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline succeeded. Node.js app deployed to AWS EC2.'
        }
        failure {
            echo 'Pipeline failed. Check the logs for errors.'
        }
    }
}
